export default {
  leftInput: document.querySelector("#left_input"),
  rightInput: document.querySelector("#right_input"),
  leftCurrency: document.querySelector("#left-cur-text"),
  rightCurrency: document.querySelector("#right-cur-text"),
  centerArrows: document.querySelector("#center"),
  currencyRightInfo: document.querySelector("#right_cur"),
  currencyLeftInfo: document.querySelector("#left_cur"),
  currencyListLeft: document.querySelector("#cur-list-left"),
  allCurrenciesLeft: document.querySelector("#all-currencies-left"),
  allCurrenciesRight: document.querySelector("#all-currencies-right"),
  currencyListRight: document.querySelector("#cur-list-right"),
  arrowLeft: document.querySelector("#left-less"),
  arrowRight: document.querySelector("#right-less"),
  arrowCenterLeft: document.querySelector("#arrow-left"),
  arrowCenterRight: document.querySelector("#arrow-right"),
  currencyInput: document.querySelectorAll("#cur-input"),
};
